name: Sukka Friends

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 17 * * *"

jobs:
  build:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: pnpm/setup@v2
        with:
          install: false
          cache: true
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          check-latest: true
          package-manager-cache: false
      - run: pnpm config set --location=global minimumReleaseAge 0
      - run: pnpm i
      - run: pnpm run build
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=sukka-friends --commit-dirty=true --branch=main
          wranglerVersion: latest
